import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { RestApiProvider } from "@/pkg/libraries/rest-api";

import { type Locale, NextIntlClientProvider } from "next-intl";
import Header from "@/app/(client)/widgets/header/header.component";
import { FC, ReactNode } from "react";

interface IProps {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<Readonly<IProps>> = async (props) => {
  const { children, params } = props;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={(await params).locale}>
          <RestApiProvider>
            <Header />

            {children}
          </RestApiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
